"""Shared Verilog utility functions."""

import math
from datetime import datetime


def clog2(value: int) -> int:
    """Ceiling log2, same as $clog2 in Verilog."""
    if value <= 1:
        return 1
    return math.ceil(math.log2(value))


def file_header(module_name: str, description: str) -> str:
    date_str = datetime.now().strftime("%Y-%m-%d")
    return (
        f"// =============================================================================\n"
        f"// Module : {module_name}\n"
        f"// Description : {description}\n"
        f"// Generated by : sram_mem_gen (mem_gen.py)\n"
        f"// Date : {date_str}\n"
        f"// =============================================================================\n"
    )
